export const boardGameActions = {
    SET_PLAYERES: 'SET_PLAYERES',
    SET_CURRENT_PLAYER: 'SET_CURRENT_PLAYER',
    UPDATE_BOARD: 'UPDATE_BOARD',
    SET_WINNER: 'SET_WINNER',
    RESET_STATE: 'RESET_STATE',
};
